baseURL = "https://fabianjetzinger.github.io/"
locale = "en-us"
title = "Fabian Jetzinger"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Fabian Jetzinger"
  description = "PhD student in Bioinformatics, focused on long-read RNA-seq, protein functions, and deep learning."
  github = "FabianJetzinger"
  email = "jetzinger.fabian@gmail.com"
  url = "https://fabianjetzinger.github.io/"
  location = "Valencia, Spain"
  keywords = "bioinformatics, long-read sequencing, deep learning, NLP, data science"
  rss = false
  lastmod = true
  favicon = "/images/github-mark.png"
  headerIcon = "/images/github-mark-white.png"
  enableSearch = false
  enableGitalk = false
  avatar = "/images/avatar.png"
  linkedin = "fabian-jetzinger"
  cvFile = "/files/fabian-jetzinger-cv.pdf"

[[params.links]]
  title = "Google Scholar"
  href = "https://scholar.google.com/citations?hl=en&user=4tXf-NwAAAAJ"
  icon = "/images/googlescholar.svg"

[[params.links]]
  title = "ORCID"
  href = "https://orcid.org/0009-0000-3150-2167"
  icon = "/images/orcid.svg"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false
